import 'dart:math';

class TextGen {
  static final Random _random = Random();

  static String generateAttack(String heroName, String enemyName) {
    final verbs = ['lunged at', 'swung at', 'smashed', 'stabbed', 'sliced'];
    final adjectives = ['vicious', 'clumsy', 'swift', 'brutal', 'sneaky'];
    final bodyParts = ['knee', 'head', 'arm', 'shield', 'chest'];

    final verb = verbs[_random.nextInt(verbs.length)];
    final adjective = adjectives[_random.nextInt(adjectives.length)];
    final bodyPart = bodyParts[_random.nextInt(bodyParts.length)];

    return "$heroName $verb the $adjective $enemyName, hitting its $bodyPart!";
  }

  static String generateQuestStart(String heroName, String questTitle) {
    return "$heroName has departed for: $questTitle.";
  }

  static String generateQuestSuccess(String heroName, String questTitle) {
    return "$heroName returned victorious from $questTitle!";
  }

  static String generateQuestFailure(String heroName, String questTitle) {
    return "$heroName returned defeated from $questTitle, barely escaping with their life.";
  }

  static String generateHeroName() {
    final names = [
      // --- Original List ---
      'Aldric',
      'Baldric',
      'Cedric',
      'Derrick',
      'Edric',
      'Fredric',
      'Godric',
      'Henderick',
      'Kendrick',
      'Ludovic',
      'Roderick',
      'Theodoric',
      'Ulric',
      'Wulfric',
      'Alaric',
      'Beric',
      'Cerdic',
      'Eadric',
      'Osric',
      'Aethelric',
      'Gareth',
      'Gawain',
      'Lancelot',
      'Percival',
      'Tristan',
      'Arthur',
      'Bedivere',
      'Bors',
      'Galahad',
      'Kay',
      'Roland',
      'Oliver',
      'Charlemagne',
      'Siegfried',
      'Beowulf',
      'Hrothgar',
      'Wiglaf',
      'Sigmund',
      'Sigurd',
      'Fafnir',
      'Thorin',
      'Fili',
      'Kili',
      'Balin',
      'Dwalin',
      'Oin',
      'Gloin',
      'Dori',
      'Nori',
      'Ori',
      'Bifur',
      'Bofur',
      'Bombur',
      'Aragorn',
      'Boromir',
      'Faramir',
      'Legolas',
      'Gimli',
      'Gandalf',
      'Frodo',
      'Samwise',
      'Merry',
      'Pippin',
      'Bilbo',
      'Elrond',
      'Galadriel',
      'Arwen',
      'Eowyn',
      'Eomer',
      'Theoden',
      'Conan',
      'Kull',
      'Bran',
      'Cormac',
      'Finn',
      'Oisin',
      'Diarmuid',
      'Grainne',
      'Deirdre',
      'Maeve',
      'Sven',
      'Bjorn',
      'Erik',
      'Leif',
      'Olaf',
      'Knut',
      'Harald',
      'Magnus',
      'Ivar',
      'Ragnar',
      'Jorin',
      'Kael',
      'Zix',
      'Flask',
      'Thae',
      'Sylas',
      'Hrolf',
      'Borin',
      'Tybalt',
      'Vane',
      'Grog',
      'Rurg',
      'Shade',
      'Vex',
      'Aric',
      'Sol',
      'Xar',
      'Malos',
      'Barns',
      'Odo',
      'Omen',
      'Nyx',
      'Gaz',
      'Rix',
      'Draven',
      'Krell',
      'Hagra',
      'Morwen',
      'Sigrid',
      'Brida',
      'Crow',
      'Leach',
      'Oryn',
      'Quinn',
      'Meph',
      'Kairn',
      'Oaken',
      'Fern',
      'Mudge',
      'Patch',
      'Sever',
      'Bane',
      'Fable',
      'Lute',
      'Crag',
      'Slate',
      'Silas',
      'Varik',
      'Pike',
      'Flint',
      'Vosh',
      'Zealo',
      'Tao',
      'Jin',
      'Vrokk',
      'Kain',
      'Zara',
      'Myst',
      'Pip',
      'Wil',
      'Locke',
      'Cole',
      'Ash',
      'Cinder',
      'Rattle',
      'Grim',
      'Merric',
      'Bram',
      'Luz',
      'Sariel',
      'Bip',
      'Zook',
      'Gorm',
      'Dirt',
      'Fang',
      'Claw',
      'Etch',
      'Rune',
      'Vrax',
      'Ignis',
      'Ren',
      'Kai',
      'Sahar',
      'Dune',
      'Jinx',
      'Mock',
      'Wynn',
      'Grace',
      'Wisp',
      'Pale', 'Gruntus', 'Krundle',
      'Brutus', 'Gann', 'Petal', 'Glint', 'Silk', 'Gilder', 'Vance', 'Colt',
    ];
    return names[_random.nextInt(names.length)];
  }
}
